theme: jekyll-theme-minimal
name: Beautifier

description: Simple library to cleanup and prettify url patterns and emails 

avatar: http://labtocat.github.io/beautifier/assets/logo.png
title-img: http://labtocat.github.io/beautifier/assets/logo.png
logo : http://labtocat.github.io/beautifier/assets/logo.png
